local theme = require("ui.kdark").colors

return {
    CmpItemKindConstant = { fg = theme.bright_red },
    CmpItemKindFunction = { fg = theme.bright_magenta },
    CmpItemKindIdentifier = { fg = theme.bright_black },
    CmpItemKindField = { fg = theme.bright_black },
    CmpItemKindVariable = { fg = theme.bright_cyan },
    Special = { fg = theme.bright_blue },
    CmpItemKindSnippet = { fg = theme.red },
    CmpItemKindText = { fg = theme.bright_yellow },
    CmpItemKindStructure = { fg = theme.bright_cyan },
    CmpItemKindType = { fg = theme.bright_green },
    CmpItemKindKeyword = { fg = theme.white },
    CmpItemKindMethod = { fg = theme.bright_magenta },
    CmpItemKindConstructor = { fg = theme.blue },
    CmpItemKindFolder = { fg = theme.white },
    CmpItemKindModule = { fg = theme.bright_green },
    CmpItemKindProperty = { fg = theme.bright_black },
    CmpItemKindUnit = { fg = theme.bright_cyan },
    CmpItemKindFile = { fg = theme.white },
    CmpItemKindColor = { fg = theme.red },
    CmpItemKindReference = { fg = theme.magenta },
    CmpItemKindStruct = { fg = theme.bright_cyan },
    CmpItemKindOperator = { fg = theme.magenta },
    CmpItemKindTypeParameter = { fg = theme.bright_black },
}
